### ISSUE TITLE
Feature Development and Requirements

### ISSUE THREAD

**Issue by Cosmonaut-itc** [Cosmonaut-itc/Lert-Team-1#10]
ET: 1 week

Drive: https://docs.google.com/document/d/1wRze2ofXtMbLlKrWiuC6lvwk5qhOdrigHCNvYWYVmpU/edit?usp=sharing

Requirements developed for Lert project.

**Comment by MedinaJacob** [comment]
por cierto  pueden mover su auditoria a progress, tienen que hacer modificaciones  https://docs.google.com/spreadsheets/d/1Ky_ZJugJ0ba4dCVFxwouF2Gmn4aqJ-S_/edit?usp=sharing&ouid=100731951882996739001&rtpof=true&sd=true

**Comment by Cosmonaut-itc** [comment]
> ¿Se puede hacer accesos a solo las personas que tienen link por favor?

Claro, podemos hacer el git privado, pero solamente pueden entrar los agregados por correo.

**Comment by MedinaJacob** [comment]
> 

bien, pero no se les olviden agregar  a todos los implicados en esto ya que el si es algo importante al momento de revisar links puede afectar al final. por ejemplo la revision de los features y la de las auditorias (vean su revisión que les agregue y comuniquense en caso de dudas con Alec ya que el esta a cargo de explicar los cambios).

**Comment by Cosmonaut-itc** [comment]
> bien, pero no se les olviden agregar a todos los implicados en esto ya que el si es algo importante al momento de revisar links puede afectar al final. por ejemplo la revision de los features y la de las auditorias (vean su revisión que les agregue y comuniquense en caso de dudas con Alec ya que el esta a cargo de explicar los cambios).

Claro, ya les pedimos sus usuarios a todos los implicados. En qué parte nos puso la revisión por cierto?

**Comment by MedinaJacob** [comment]
> > bien, pero no se les olviden agregar a todos los implicados en esto ya que el si es algo importante al momento de revisar links puede afectar al final. por ejemplo la revision de los features y la de las auditorias (vean su revisión que les agregue y comuniquense en caso de dudas con Alec ya que el esta a cargo de explicar los cambios).
> 
> Claro, ya les pedimos sus usuarios a todos los implicados. En qué parte nos puso la revisión por cierto?

En la de su auditoria que les movi en progress, porque tienen que hacer los cambios y correciones

**Comment by MedinaJacob** [comment]
Aprobado
